name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v .
      - name: install lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # See https://github.com/actions/setup-go/issues/14
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: lint
        run: golangci-lint run
      - name: test
        run: go test ./... -v
