name: Go
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
env:
  GOLANGCI_LINT_VERSION: v1.23.8

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.14.1]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v .
      - name: install lint
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}
      - name: lint
        run: golangci-lint run ./... -v
      - name: test
        run: go test ./... -update true -v
